public class IdentifiableClient
{
	public String Ref {get;set;}
	public String FirstName {get;set;}
	public String LastName {get;set;}
	public Contact details {get;set;}
	public Date FirstReferralDate {get;set;}
	public Date StartDateFirstMeeting {get;set;}
	public Date OutcomeDate {get;set;}
	public String OutcomeStatus {get;set;}
	public Date DateDiscontinued {get;set;}
	public Date DateCompleted {get;set;}
	public String Status {get;set;}
	public String ReasonDiscontinued {get;set;}
	public String ProbationOfficer {get;set;}
	public String Owner {get;set;}
	public String lineMonth {get;set;}
	public Integer lineYear {get;set;}
	public String referralID {get; set;}
	public String referredFrom {get; set;}
	public String referredFor {get; set;}
}